-- AlterTable
ALTER TABLE `tasks` ADD COLUMN `created_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    ADD COLUMN `job_status` ENUM('OPEN', 'IN_PROGRESS', 'AWAITING_REVIEW', 'COMPLETED') NOT NULL DEFAULT 'OPEN',
    ADD COLUMN `updated_at` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);
